# Generated by Django 4.2.1 on 2023-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('election_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('list_of_candidates', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('one_time_wallet', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=150)),
                ('private_key', models.CharField(max_length=150)),
                ('nonce', models.IntegerField()),
            ],
        ),
    ]
