# Generated by Django 4.2.1 on 2023-05-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_campaign_wallet_weight_arrays_vote_new_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='notification_per_user',
        ),
    ]
