version: '3'

services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
    ports:
      - "8000:8000"